name: Build apps

on:
  workflow_dispatch:

jobs:

  build-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker run --rm -v ${{ github.workspace }}/build:/build -v ${{ github.workspace }}/apps:/apps ghcr.io/jbatonnet/rinkhals/build /bin/bash -c "chmod +x /build/build-swu.sh && /build/build-swu.sh /apps/example"
      - uses: actions/upload-artifact@v4
        with:
          name: app-example.swu
          path: |
            build/dist/update.swu
